config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cookbook#index"
  resources :cookbook
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cookbook.rb
class Cookbook < ApplicationRecord
  belongs_to :user
  belongs_to :dish, required: false

  validates :name, presence: true, uniqueness: true, length: {
    maximum: 30,
    too_long: "maximum length is 50 characters.",
    minimum: 5,
    too_short: "inimum length is 5 characters"
  }
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :users, through: :cookbook
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dishes, through: :cookbook
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cookbook_controller.rb
class CookbookController < ApplicationController
  before_action :authenticate_user!

  def index
    @cookbooks = Cookbook.all
    @new_cookbook = Cookbook.new
  end

  def show
    @cookbook = Cookbook.find(params[:id])
  end

  def new
    @cookbook = Cookbook.new
  end

  def create
    @new_cookbook = Cookbook.new(cookbook_params)
    @new_cookbook.user = current_user
    @new_cookbook.valid? ? @new_cookbook.save : raise
  end

  def edit
  end

  def destroy
  end

  def update
  end

  private

  def cookbook_params
    params.require(:cookbook).permit(:id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/views/cookbook/index.html.erb
<div class="container">
  <h5>Your cookbooks</h5>

  <% if @cookbooks.present? %>
    <% @cookbooks.each { |cookbook|  %>
      <%= cookbook.name %>
    <% } %>
  <% else %>
    <p>Your cookbook list is empty</p>
  <% end %>

  <div data-controller="newCookbook">
    <button class="btn btn-primary" data-newCookbook-target="button" data-action="click->newCookbook#toggleForm">Add cookbook</button>

    <%= render partial: 'shared/cookbook_form', object: @new_cookbook %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookcook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_cookbook_form.html.erb
<div class="cookbook-form d-none" data-newCookbook-target="form">
  <%= simple_form_for @new_cookbook, url: cookbook_index_path do |f| %>
    <%= f.input :name,
      error: "Name must have between 5 and 30 characters",
      required: true,
      input_html: { minLength: 5, maxLength: 30},
      input_html: { data: { action: "keyup->newCookbook#validate", target: "newCookbook.border" } }%>

    <%= f.submit "Create cookbook" %>
  <% end %>
</div>